# Generated by Django 3.0.4 on 2020-03-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OHLCVC',
            new_name='OHLC',
        ),
    ]
