# Generated by Django 3.0.4 on 2020-03-23 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('accNo', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('hogaType', models.CharField(max_length=2)),
                ('orderNo', models.CharField(max_length=10)),
                ('orderType', models.CharField(max_length=2)),
                ('originOrderNo', models.CharField(max_length=10)),
                ('rqName', models.CharField(max_length=30)),
                ('scrNo', models.CharField(max_length=4)),
                ('msg', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
