# Generated by Django 3.0.4 on 2020-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200308_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlc',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohlc',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohlc',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohlc',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohlc',
            name='volume',
            field=models.FloatField(),
        ),
    ]
